### ISSUE TITLE
Add testing framework to react-hcaptcha

### ISSUE THREAD

**Issue by alikoneko** [hCaptcha/react-hcaptcha#1] opened 2018-12-21 17:16 UTC
- pick testing framework (Jest, Mocha, etc)
- add some integration and unit testing similar to what is being added to vue-hcaptcha

**Comment by DSergiu** [comment] 2021-02-01 18:17
Duplicate of https://github.com/hCaptcha/react-hcaptcha/issues/64

**Closed by DSergiu** 2021-02-01 18:17 UTC
