### ISSUE TITLE
[hCaptcha] render: invalid container 'null'.

### ISSUE THREAD

**Issue by abdulsamad** [hCaptcha/react-hcaptcha#63] opened 2021-01-09 08:35 UTC
hCaptcha is not a rendering giving an error "[hCaptcha] render: invalid container 'null'".

Browser - Chrome (v87.0.4280.141)
Technologies -
Gatsby
Styled-components

```jsx
{/* Fails to render */}
<Contact id='contact'>
      <Container>
        <Form name='contact' onSubmit={handleSubmit}>
          <FormHeading>Get in touch!</FormHeading>
          {error && <Error>{error}</Error>}
          <Field>
            <Input
              type='text'
              placeholder='Your Name'
              name='name'
              onChange={handleChange('name')}
              required
            />
            <Label>Name</Label>
            <span />
          </Field>
          <Field>
            <Input
              type='email'
              placeholder='john@example.com'
              name='email'
              onChange={handleChange('email')}
              required
            />
            <Label>Email</Label>
            <span />
          </Field>
          <Field>
            <Textarea
              rows={5}
              placeholder='Enter your message here...'
              name='message'
              onChange={handleChange('message')}
              required
            />
            <Label>Message</Label>
            <span />
          </Field>
         {/* Field is a div tag */}
          <Field>
            <HCaptcha
              ref={hCaptchaRef}
              sitekey={process.env.GATSBY_SITE_RECAPTCHA_KEY}
              onVerify={handleCaptchaSuccess}
              onExpire={handleCaptchaExpire}
              onError={handleCaptchaError}
              theme='dark'
            />
          </Field>
          <SubmitBtn type='submit'>Send</SubmitBtn>
        </Form>
      </Container>
 </Contact>
```

it only works after wrapping it in a form tag without any sibling. The nesting of the form tag is also not valid I guess.

```jsx
{/* Works */}
<Contact id='contact'>
      <Container>
        <Form name='contact' onSubmit={handleSubmit}>
          <FormHeading>Get in touch!</FormHeading>
          {error && <Error>{error}</Error>}
          <Field>
            <Input
              type='text'
              placeholder='Your Name'
              name='name'
              onChange={handleChange('name')}
              required
            />
            <Label>Name</Label>
            <span />
          </Field>
          <Field>
            <Input
              type='email'
              placeholder='john@example.com'
              name='email'
              onChange={handleChange('email')}
              required
            />
            <Label>Email</Label>
            <span />
          </Field>
          <Field>
            <Textarea
              rows={5}
              placeholder='Enter your message here...'
              name='message'
              onChange={handleChange('message')}
              required
            />
            <Label>Message</Label>
            <span />
          </Field>
          <form>
            <HCaptcha
              ref={hCaptchaRef}
              sitekey={process.env.GATSBY_SITE_RECAPTCHA_KEY}
              onVerify={handleCaptchaSuccess}
              onExpire={handleCaptchaExpire}
              onError={handleCaptchaError}
              theme='dark'
            />
          </form>
          <SubmitBtn type='submit'>Send</SubmitBtn>
        </Form>
      </Container>
 </Contact>
```

**Comment by Johann-S** [comment] 2021-01-31 16:31
I have the same error but only when I pass query params in my URL and with Gatsby too

**Comment by DSergiu** [comment] 2021-02-01 14:02
I am not able to reproduce this issue. Please share a more detailed scenario and the versions of `hcaptcha`, `gatsby` etc. @abdulsamad 

The error `"[hCaptcha] render: invalid container 'null'".` happens probably because of some sort of gatsby encapsulation of the `hcaptcha` dom element and `document.findElementById` cannot find it.

**Comment by Johann-S** [comment] 2021-02-01 14:20
I have this error with Gatsby v2.30.3 and hcaptcha/react-hcaptcha 0.3.0

**Comment by abdulsamad** [comment] 2021-02-01 19:21
> I am not able to reproduce this issue. Please share a more detailed scenario and the versions of `hcaptcha`, `gatsby` etc. @abdulsamad
> 
> The error `"[hCaptcha] render: invalid container 'null'".` happens probably because of some sort of gatsby encapsulation of the `hcaptcha` dom element and `document.findElementById` cannot find it.

chorme - 88.0.4324.96
gatsby - 2.26.1
styled-components - 1.12.0
@hcaptcha/react-hcaptcha - 0.2.2
react & react-dom - 16.12.0
yarn (v1.22.10)

**Comment by DSergiu** [comment] 2021-02-02 13:13
Please try version `0.3.2` and let me know if it solves your issue.

`npm install -S @hcaptcha/react-hcaptcha@0.3.2`

@abdulsamad @Johann-S

**Comment by abdulsamad** [comment] 2021-02-02 13:42
It's working in @hcaptcha/react-hcaptcha@0.3.2
Thank you so much @DSergiu

**Comment by Johann-S** [comment] 2021-02-02 13:55
it's working thanks @DSergiu 👍

**Comment by DSergiu** [comment] 2021-02-02 14:55
Super. I will close this as it seems to be resolved.

**Closed by DSergiu** 2021-02-02 14:55 UTC
